### ISSUE TITLE
How to have a new task or note created in Highrise every time form is submitted

### ISSUE THREAD

**Issue by ghost** [katzwebservices/Gravity-Forms-Highrise-Addon#5]
Thank you for your plugin but I can't seem to figure out how to make this important action for me.

I have an online "book your maid" form. The first time the form is filled, all the info is put into Highrise. But everytime after the customer fills out the form to book a maid, I need to have a new task (or even a new note) to be created in Highrise. How can I make this happen? I have tried adding the sNotes parameter to my cleaning instructions field but it does add it as a new note.  

Ryan

**Comment by zackkatz** [comment]
You should try http://wordpress.org/plugins/gravity-forms-highrise-crm/ instead.

**Comment by ghost** [comment]
Thanks for the response. I tried the other plugin but it does the exact same. I remembered I can add a GF notification using the Highrise dropbox email and also task emails.
